### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JDeuce** [SradnickDev/GridBasedBuilding#2]
Cool project man. I've considering attempting to play around replicate something like their build progress shader in Unity and thought that this might make a good base. 

I couldn't find a license in the repo, can you clarify the terms this is released under? GPL? BSD? Apache? WTFPL? 

Thanks.

**Comment by SradnickDev** [comment]
You can use it in anyway you want.

**Comment by JDeuce** [comment]
cool, might be a good idea to just throw some kind of license into the repo too, maybe like this one http://www.wtfpl.net/txt/copying/

**Comment by SradnickDev** [comment]
lol, ya ok
